language: ruby
rvm:
  - 2.4.2

script: 'bundle exec rake test:unit'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential
  - gem update --system
  - gem --version
  - gem update bundler

after_failure: "cat /home/travis/build/tillsc/multi_markdown/ext/mkmf.log"